if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config();
}

export default {
  PORT: process.env.PORT || 4000,
  COSMOS_ENDPOINT: process.env.COSMOS_ENDPOINT,
  COSMOS_KEY: process.env.COSMOS_KEY,
  COSMOS_CONTAINER: process.env.COSMOS_CONTAINER,
  COSMOS_TABLE_CLINICARECORD: process.env.COSMOS_TABLE_CLINICARECORD,
  COSMOS_TABLE_INVOICE: process.env.COSMOS_TABLE_INVOICE,
  COSMOS_TABLE_MEETING: process.env.COSMOS_TABLE_MEETING,
  MAX_ITEM_COUNT_CLINICARECORD: process.env.MAX_ITEM_COUNT_CLINICARECORD,
  MAX_ITEM_COUNT_DOCUMENT: process.env.MAX_ITEM_COUNT_DOCUMENT,
  MAX_ITEM_COUNT_INVOICE: process.env.MAX_ITEM_COUNT_INVOICE,
  COSMOS_TABLE_DOCUMENT: process.env.COSMOS_TABLE_DOCUMENT,
  AZURE_STORAGE_CONNECTION_STRING: process.env.AZURE_STORAGE_CONNECTION_STRING,
  SFTP_CONNECT_HOST: process.env.SFTP_CONNECT_HOST,
  SFTP_CONNECT_PORT: process.env.SFTP_CONNECT_PORT,
  SFTP_CONNECT_USERNAME: process.env.SFTP_CONNECT_USERNAME,
  SFTP_CONNECT_PASSWORD: process.env.SFTP_CONNECT_PASSWORD,
  SFTP_PATHNAME_EXPEDIENTE_DIGITAL: process.env.SFTP_PATHNAME_EXPEDIENTE_DIGITAL,
};
